### PR TITLE
Chore: devcontainer cleanups, update python version

### PR DESCRIPTION
**Pull request by thekaveman**
* Fixes syntax in devcontainer.json
* Applies the same fix from e.g. https://github.com/compilerla/compiler.la/pull/227
* Updates base image to Python 3.11 by default
* Build arg to allow custom Python versions
* Push multiple versions to GHCR
* Update docs, including to link to our blog post on this subject from @machikoyasuda 

:green_circle: I ran the workflow manually here: https://github.com/compilerla/template-devcontainer/actions/runs/9912876071

The newly tagged version images were built and pushed to GHCR:

* [`main`](https://github.com/compilerla/template-devcontainer/pkgs/container/template-devcontainer/243050633?tag=main) (now Python 3.11)
* [`main_3.10`](https://github.com/compilerla/template-devcontainer/pkgs/container/template-devcontainer/243050635?tag=main_3.10)
* [`main_3.12`](https://github.com/compilerla/template-devcontainer/pkgs/container/template-devcontainer/243050617?tag=main_3.12)

### CODE REVIEW

**Review by angela-tran — APPROVED** [review]
These changes look good to me!

Would it make sense to add multi-platform support to this template devcontainer? Like what was done in [cal-itp/docker-python-web #36](https://github.com/cal-itp/docker-python-web/pull/36/files)

**Comment by thekaveman** [comment]
@angela-tran

> Would it make sense to add multi-platform support to this template devcontainer? Like what was done in [cal-itp/docker-python-web #36](https://github.com/cal-itp/docker-python-web/pull/36/files)

Great suggestion / catch! This would have been annoying for @lalver1 and @machikoyasuda trying to use this devcontainer!

Added in [`6008fc1`](https://github.com/compilerla/template-devcontainer/pull/34/commits/6008fc16d37d96b051747b404106f06ef4c33402).

**Review by angela-tran — APPROVED** [review]
🚀

**Comment by lalver1** [comment]
Looks good to me too! And thanks for the multi-platform support 😄

**Pull request merged**
